### ISSUE TITLE
How to create new HDF5 Files for running VQE calculations

### ISSUE THREAD

**Issue by jason-jk-kang** [Qiskit/qiskit-chemistry#132]
### Informations

- **Qiskit Chemistry version**: Version: 0.4.2
- **Python version**: 3.6.8
- **Operating system**: Linux

### What is the current behavior?
I have successfully run the example on the front page of qiskit-chemistry to calculate for an h2 molecule. I would like to run this computation for different molecules, but I am not sure how.

It is my understanding that we require a HDF5 for every molecule we compute for. This HDF5 is the driver. My question is whether the function PySCFDriver is meant to create this HDF5 or do we need the HDF5 in order to run PYSCFDriver on, say, a new experiment H3.

driver = PySCFDriver(atom='H .0 .0 .0; H .0 .0 0.735;  H .0 .0 3.3')
                    unit=UnitsType.ANGSTROM,
                    basis='sto3g')

Any help is appreciated. Basically I just want to learn how to use qiskit-chemistry for different molecules and I think the issue I'm facing currently is not understanding how to interface with drivers.

**Comment by woodsp-ibm** [comment]
If you have a chemistry driver installed, such as PySCF then you do not need an HDF5 file. The HDF5 file is the stored output from a prior run with an actual chemistry driver that can be used with our built in HDF5Driver. The notebooks you see in main qiskit tutorials HDF5 files we created so that they could run without the need to separately install a driver such as PySCF, PSI4 etc.
If you have done 'pip install pyscf' then you can run with that driver. And indeed when running you can store the driver output as an HDF5 file for your own later use. Does that help?

**Comment by jason-jk-kang** [comment]
This is helpful! I have been working with PySCF, but if I want to run a different molecule is it the case that I just need to run

```
driver = PySCFDriver(atom='H .0 .0 .0; H .0 .0 0.735; H .0 .0 3.3')
unit=UnitsType.ANGSTROM,
basis='sto3g')
```

As in, is the string input for "atom" the only thing I need to change to specify any new molecule?

I am confused because when I do run this, I get an error reading 

RuntimeError: Electron number 3 and spin 0 are not consistent
Note mol.spin = 2S = Nalpha - Nbeta, not 2S+1

**Comment by jason-jk-kang** [comment]
Apologies, I updated the spin to 1 and I am now getting 

`
Traceback (most recent call last):
  File "/home/jasonkang/anaconda3/envs/QiskitDevenv/lib/python3.6/site-packages/qiskit_chemistry/drivers/pyscfd/integrals.py", line 56, in compute_integrals
    ehf, enuke, norbs, mohij, mohijkl, mo_coeff, orbs_energy, x_dip, y_dip, z_dip, nucl_dip = _calculate_integrals(mol, calc_type)
  File "/home/jasonkang/anaconda3/envs/QiskitDevenv/lib/python3.6/site-packages/qiskit_chemistry/drivers/pyscfd/integrals.py", line 177, in _calculate_integrals
    elec_dip = np.negative(np.einsum('xij,ji->x', ao_dip, dm).real)
  File "/home/jasonkang/anaconda3/envs/QiskitDevenv/lib/python3.6/site-packages/numpy/core/einsumfunc.py", line 1228, in einsum
    return c_einsum(*operands, **kwargs)
ValueError: operand has more dimensions than subscripts given in einstein sum, but no '...' ellipsis provided to broadcast the extra dimensions.`

I am still curious as to whether running an experiment on a new molecule amounts to just changing the name of the atom. Thank you!

**Comment by woodsp-ibm** [comment]
Currently we only support molecules with spin=0 for PySCF (multiplicity 1) since we use rhf. There are more examples in community\aqua\chemistry of other molecules. So H2 we can do but not H3 at present. LiH is a bit larger if you'd like to try that.
In general in changing a molecule you would need the name, spin and charge. But for now, as I explained the molecules we can support need to have the same number of alpha and beta electrons, ie for PySCF that means spin=0 (other drivers its multiplicity = 1)

**Comment by pistoia** [comment]
Hi @jason-jk-kang, as @woodsp-ibm explained, you do not need to use HDF5 files if you have already installed one of the classical computations chemistry software packages interfaced by Aqua.  These include PSI4, PyQuante, PySCF and Gaussian.  It looks like you already have PySCF so you are good to go.

In terms of extending the basic H2 simulation code to larger molecules, I recommend that you look at our tutorials in https://github.com/Qiskit/qiskit-tutorials/tree/master/qiskit/aqua/chemistry and https://github.com/Qiskit/qiskit-tutorials/tree/master/community/aqua/chemistry assuming you are using Qiskit Chemistry from PyPI.  If you have cloned Qiskit Chemistry and Qiskit Aqua from their GitHub repositories, then you should look at our WIP qiskit-tutorials repository fork (git@github.com:manoelmarques/qiskit-tutorials.git), because the tutorials here are in sync with Qiskit Aqua and Qiskit Chemistry from master.  Specifically, you will find here numerous examples on how to simulate molecules behind H2, such as LiH, NaH, BeH2 and even H2O.

You will see that it is not always enough to just change the molecular configuration from H2 to another molecule.  Take, for example, the notebook on LiH described at https://github.com/Qiskit/qiskit-tutorials/blob/master/qiskit/aqua/chemistry/programmatic_approach.ipynb
Here you will see, for example, that we freeze the core of the molecule and remove some unoccupied orbitals from the computation by virtue of these two instructions:
```
freeze_list = [0]
remove_list = [-3, -2] 
```
This shows that you cannot reuse the same code to simulate different molecules by changing only the molecular configuration, since different molecules may have different frozen cores and/pr unoccupied orbitals to be removed.

**Comment by woodsp-ibm** [comment]
Since I believe this discussion is concluded I am closing this issue. If you wish to discuss 
further or have other topics that you wish to cover please feel to post to the public Qiskit
Slack workspace in the #aqua channel there. If you are not a member of this workspace you can
find a 'Join the Slack community' button link on the qiskit.org home page to click to be invited.
